site_name: DFIN

theme:
  name: material
  palette:
    primary: deep-orange
  features:
    - navigation.instant

nav:
  - Evaluación:
    - General: index.md
    - Seminario: seminario.md
  - Tema 1: tema-1/index.md
  - Tema 2:
    - Teoría: tema-2/index.md
    - Ejemplos: tema-2/ejemplos.md
    - Problemas: tema-2/problemas.md
  - Tema 3:
    - Índice: tema-3/index.md
    - 1. Estructura de capital e impuestos: tema-3/3.1.md
    - 2. Estructura de capital y costes de solvencia: tema-3/3.2.md
    - 3. Estructura de capital y el modelo de equilibrio de activos financieros: tema-3/3.3.md
    - 4. Estructura de capital y relaciones de agencia: tema-3/3.4.md
    - 5. Estructura de capital y opciones: tema-3/3.5.md

repo_name: team-ittade/dfin2
repo_url: https://github.com/team-ittade/dfin2

extra_css:
    - css/colors.css
    - css/custom.css
    - css/termynal.css

extra_javascript:
    - js/config.js
    - js/custom.js
    - js/links.js
    - js/tables.js
    - js/termynal.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - def_list
  - extra
  - extra
  - footnotes
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: 🔗
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - search
